# Generated by Django 2.0.7 on 2018-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='category',
            field=models.IntegerField(choices=[(1, 'Reinforcement of needs'), (2, 'Memebership'), (3, 'Influence'), (4, 'Shared Emotional Connection')], default=1),
            preserve_default=False,
        ),
    ]
