# Generated by Django 2.0.7 on 2018-07-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0002_auto_20180712_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyQuestionCategory',
        ),
    ]
