# Generated by Django 2.0.7 on 2018-07-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0003_delete_surveyquestioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pamoja.Group'),
        ),
    ]
