# Generated by Django 2.0.7 on 2018-07-12 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0004_auto_20180712_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 12, 17, 7, 11, 442109, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
