# Generated by Django 2.0.7 on 2018-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0006_auto_20180712_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='result',
            field=models.CharField(default='[[null, null, null, null], [null, null, null, null], [null, null, null, null], [null, null, null, null]]', max_length=1000),
        ),
    ]
