# Generated by Django 2.0.7 on 2018-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0007_auto_20180713_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='result',
            field=models.CharField(default='[[], [], [], []]', max_length=1000),
        ),
    ]
