# Generated by Django 2.0.7 on 2018-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0009_auto_20180715_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_bot_url',
            field=models.URLField(null=True),
        ),
    ]
