# Generated by Django 2.0.7 on 2018-07-15 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pamoja', '0010_group_group_bot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('admin', 'group_id')},
        ),
    ]
