# Generated by Django 2.0.7 on 2018-07-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0011_auto_20180715_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_bot_url',
        ),
    ]
