# Generated by Django 2.0.7 on 2018-07-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0012_remove_group_group_bot_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinfo',
            old_name='created',
            new_name='created_on',
        ),
    ]
