# Generated by Django 2.0.7 on 2018-07-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamoja', '0014_auto_20180721_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='group',
        ),
    ]
