# Generated by Django 2.0.7 on 2018-07-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_facebookuser_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
