# Generated by Django 2.0.7 on 2018-07-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180721_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='facebook_id',
            field=models.CharField(max_length=200),
        ),
    ]
