# Generated by Django 2.0.7 on 2018-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180722_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='access_token',
            field=models.CharField(max_length=1000),
        ),
    ]
