# Generated by Django 2.0.7 on 2018-07-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180722_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='facebook_id',
            field=models.CharField(max_length=1000),
        ),
    ]
