# Generated by Django 2.0.7 on 2018-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_botuser_current_survey_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='current_group_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
