# Generated by Django 2.0.7 on 2018-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_botuser_current_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='current_group_id',
            field=models.IntegerField(null=True),
        ),
    ]
