# Generated by Django 2.0.7 on 2018-07-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_botuser_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='invited',
        ),
    ]
